name: Shared Builder

on:
  workflow_call:
    inputs:
      image:
        description: Name of image
        type: string
        required: true
#    secrets:
#      GITHUB_TOKEN:
#        required: true


defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Checkout reusable workflows repository
        uses: actions/checkout@v3
        with:
          repository: vholer/test-ghw-shared
          path: reusable-repo
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
          submodules: false

      - name: Build
        id: build
        run: echo Build

      - name: Test
        id: test
        run: |
          find .
          reusable-repo/.github/scripts/test.sh
