name: Shared Builder

on:
  workflow_call:
    inputs:
      image:
        description: Name of image
        type: string
        required: true
#    secrets:
#      GITHUB_TOKEN:
#        required: true


defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      # We want to reference scripts from shared repo
      # https://stackoverflow.com/questions/72133102/how-to-execute-a-a-remote-script-in-a-reusable-github-workflow
      - name: Checkout reusable workflows repository
        uses: actions/checkout@v3
        with:
          repository: vholer/test-ghw-shared
          path: reusable-repo
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
          submodules: false

      - name: Build
        id: build
        run: echo Build

      - name: Test
        id: test
        run: |
          find .
          echo "${{ github.event.ref }}"
          reusable-repo/.github/scripts/test.sh
